<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>951eaffb-7fa4-457c-811a-72eea8e86b69</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\STB.Experiment.API\STB.Experiment.API.csproj" />
  </ItemGroup>

</Project>
